name: drug-response-ml
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - matplotlib
  - shap
  - jupyterlab
  - seaborn
  - pyarrow
  - pip
  - pip:
      - polars
